version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .
      args:
        user: nttduong
        uid: 1000
      dockerfile: Dockerfile.dev
    image: laravel-app
    restart: unless-stopped
    working_dir: /var/www/html/
    volumes:
      - ./:/var/www/html/
      - /var/www/vendor
    networks:
      - laravel
  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - ./:/var/www/html/
      - /var/www/node_modules
    networks:
      - laravel
    depends_on:
      - app
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - ${SERVER_PORT}:80
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d/
    networks:
      - laravel
  db:
    container_name: db
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: liverpool
      MYSQL_USER: nttduong
      MYSQL_PASSWORD: liverpool
    ports:
      - ${DATABASE_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    networks:
      - laravel
  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: liverpool
    restart: always
    networks:
      - laravel
    ports:
      - ${PHPMYADMIN_PORT}:80
volumes:
  mysql_data:
  mysql_config:
#Docker Networks
networks:
  laravel:
    driver: bridge
